import { useEffect,useState } from 'react';
import axios from 'axios';
import { useNavigate } from 'react-router-dom';
import AppShell,{SectionCard,StatCard,StatusBadge} from './AppShell';
const API=import.meta.env.VITE_API_BASE_URL||'http://localhost:3000';
export default function AdminDashboard(){const [users,setUsers]=useState([]);const [error,setError]=useState('');const navigate=useNavigate();useEffect(()=>{axios.get(`${API}/admin/users`).then(r=>setUsers(r.data.data||[])).catch(()=>setError('The admin API is not available yet. Showing the workspace with local sample activity.'))},[]);const counts={patients:users.filter(x=>String(x.role).toLowerCase()==='patient').length,doctors:users.filter(x=>String(x.role).toLowerCase()==='doctor').length,admins:users.filter(x=>String(x.role).toLowerCase()==='admin').length};const rows=users.length?users.slice(0,6):[['James K.','patient'],['Joseph M.','patient'],['Dr. Kazeze','doctor']].map((x,i)=>({id:i,fullnames:x[0],role:x[1],email:'sample@heartbud.local'}));return <AppShell role="admin" title="System overview" subtitle="Manage HeartBud accounts, workflows and operational activity.">
 <div className="hb-grid hb-grid-4"><StatCard label="Total users" value={users.length||'—'} detail="Accounts in the system" tone="blue" icon="♙"/><StatCard label="Patients" value={counts.patients||'—'} detail="Registered patient accounts" tone="teal" icon="♥"/><StatCard label="Doctors" value={counts.doctors||'—'} detail="Clinical user accounts" tone="green" icon="Dr"/><StatCard label="System status" value="Online" detail="Core portal available" tone="green" icon="✓"/></div>
 {error&&<div className="hb-alert" style={{marginTop:18}}><strong>Development mode</strong>{error}</div>}
 <div className="hb-grid hb-grid-3" style={{marginTop:18}}>
  <SectionCard title="Recent accounts" action={<button className="hb-link" onClick={()=>navigate('/admin/users')}>Manage users</button>} style={{gridColumn:'span 2'}}><table className="hb-table"><thead><tr><th>User</th><th>Role</th><th>Email</th><th>Status</th></tr></thead><tbody>{rows.map(u=><tr key={u.id}><td><div className="hb-patient-cell"><div className="hb-table-avatar">{String(u.fullnames||'HB').split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase()}</div><strong>{u.fullnames}</strong></div></td><td>{u.role}</td><td>{u.email}</td><td><StatusBadge tone="healthy">Active</StatusBadge></td></tr>)}</tbody></table></SectionCard>
  <SectionCard title="Administration shortcuts"><div className="hb-quick-actions"><button className="hb-action" onClick={()=>navigate('/admin/users')}><strong>User management</strong><span>Patients, doctors and admins</span></button><button className="hb-action" onClick={()=>navigate('/admin/activity')}><strong>Activity log</strong><span>Review system events</span></button><button className="hb-action" onClick={()=>navigate('/admin/settings')}><strong>Settings</strong><span>Portal configuration</span></button><button className="hb-action" onClick={()=>navigate('/admin/predictions')}><strong>Assessments</strong><span>Model activity</span></button></div></SectionCard>
 </div>
 <div className="hb-grid hb-grid-3" style={{marginTop:18}}><SectionCard title="Role distribution"><div className="hb-metric"><strong>Patients</strong><span>{counts.patients||0}</span></div><div className="hb-progress"><span style={{width:users.length?`${Math.round(counts.patients/users.length*100)}%`:'0%'}}/></div><div className="hb-metric"><strong>Doctors</strong><span>{counts.doctors||0}</span></div><div className="hb-progress"><span style={{width:users.length?`${Math.round(counts.doctors/users.length*100)}%`:'0%'}}/></div></SectionCard><SectionCard title="Security"><div className="hb-alert" style={{background:'#eef8f7',borderColor:'#cceae6',color:'#276c65'}}><strong style={{color:'#1b6059'}}>Use protected admin APIs</strong>Administrative actions should be authenticated and authorized server-side.</div></SectionCard><SectionCard title="System notes"><p style={{fontSize:11,color:'#718096',lineHeight:1.7,margin:0}}>The admin portal is a new layer for HeartBud V2. It does not change clinical decisions or replace doctor review.</p></SectionCard></div>
 </AppShell>}
